### ISSUE TITLE
Do you have paper and pretrained models?

### ISSUE THREAD

**Issue by zuowanbushiwo** [ilyailyash/Interaction_FullSubNet#1]
Hello
     I am very interested in your project, do you have relevant documents?
Thanks！

**Comment by ilyailyash** [comment]
Hello!
There is a published paper https://link.springer.com/chapter/10.1007/978-3-030-94141-3_8
You can see the text of the paper [here](https://books.google.ru/books?id=f7NZEAAAQBAJ&pg=PA86&lpg=PA86&dq=Two-Stage+Method+of+Speech+Denoising+by+Long+Short-Term+Memory+Neural+Network&source=bl&ots=trueQsOA_q&sig=ACfU3U1T-eZjDzgjSKHtJXTg_DdRewJZew&hl=en&sa=X&ved=2ahUKEwjOwej5y4T5AhXqkosKHbbaC08Q6AF6BAgWEAM#v=onepage&q=Two-Stage%20Method%20of%20Speech%20Denoising%20by%20Long%20Short-Term%20Memory%20Neural%20Network&f=false)

**Comment by zuowanbushiwo** [comment]
Thanks！
